### ISSUE TITLE
Small usability improvements

### ISSUE THREAD

**Issue by luhkevin** [netsil/utils#5]
Some small improvements -- along with some packaging changes (e.g. maybe we can wrap this in a docker container), I think I typically see CLI tools with a dash (-) rather than underscore ( _ ). And with the env vars listed above, it might be more readable if we add some underscores (e.g. AOC_USER, AOC_URL, AOC_PWD). Lastly, we can investigate how to better format the printed output of "alert list", and maybe even have some export options (e.g. export stdout of "alert list" to csv or something.

**Comment by ackerman80** [comment]
fixed above issues
